version: "3"
services:
  api:
    container_name: api
    image: madhavanraja/furdb
    environment:
      WORKDIR: /furdb
      PORT: 80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    develop:
      watch:
        - action: rebuild
          path: .
