version: "3"
services:
  api:
    image: madhavanraja/furdb
    environment:
      FUR_DIRECTORY: /furdb
      FURDB_PORT: 8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: .
