version: "3"
services:
  api:
    container_name: api
    image: madhavanraja/furdb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WORKDIR=/furdb
    ports:
      - "5678:80"
    develop:
      watch:
        - action: rebuild
          path: .
